dependFieldRow_5:
  ban_id: '8'
  ban_name: "\u6821\u957F\uFF0C\u522B\u518D\u90A3\u4E48\u7D2F"
  image: https:\/\/crm.mp.image.lpcollege.com\/fwh\/official\/banner\/2019-10-24\/de88ac1caa5ede52023cae58a2f7ee54.jpg
  is_show: 1
  link: https:\/\/fuwuhao.lpcollege.com\/#\/courseDetails\/1502
  sort: '13'
dependFieldRow_3:
  course_class_id: 7
  course_name: "\u6559\u57F9\u4E1A\u76C8\u5229\u9AD8\u589E\u957F\u8FD0\u8425\u6A21\
    \u5F0F3.0"
  course_name_id: 86
  course_name_sn: ZA_01_03_01
  hr_id: 2
  is_auto_refund: 1
  is_deposit: 0
  is_refund_audit: 0
  least_price: '980.00'
  member_price: '2980.00'
  meth_id: 2
  price: '2980.00'
  use_card_number: 1
dependFieldRow_7:
  nicke_name: "\u6F02\u6773"
dependFieldRow_9:
  co_id: '15738'
  order_id: '11665'
dependFieldRow_11:
  card_manage_id: 17
  least_price: '1.00'
  number: 0
  period: 36
  price: '98000.00'
  study_card_name: "\u5FAE\u7B11\u7EFF\u841D\u52A0\u76DF"
dependFieldRow_13:
  sc_code_id: '1'
dependFieldRow_15:
  auth[0]: '['
  auth[2]: '1'
  id: '3'
  name: "\u8BFE\u7A0B\u7BA1\u7406\u5458"
dependFieldRow_16: {}
