dependKeyRow_3:
- $.data.data[*].course_name_id
- $.data.data[*].course_name_sn
- $.data.data[*].course_name
- $.data.data[*].course_class_id
- $.data.data[*].price
- $.data.data[*].member_price
- $.data.data[*].least_price
- $.data.data[*].is_deposit
- $.data.data[*].hr_id
- $.data.data[*].meth_id
- $.data.data[*].use_card_number
- $.data.data[*].is_auto_refund
- $.data.data[*].is_refund_audit
- $.data.data[*].course_broker_id
- $.data.data[*].create_admin_id
- $.data.data[*].current_daiding_course_id
- $.data.data[*].is_auto_legacy
- $.data.data[*].is_put
- $.data.data[*].legacy_hours
- $.data.data[*].org_id
- $.data.data[*].perf_comp_id
- $.data.data[*].update_admin_id
- $.data.data[*].use_ticket_number
dependKeyRow_5:
- $.data.nicke_name
- $.data.timestamp
- $.data.sign
dependKeyRow_7:
- $.data.data[*].co_id
- $.data.data[*].order_id
- $.data.data[*].timestamp
- $.data.data[*].sign
dependKeyRow_9:
- $.data[*].ban_name
- $.data[*].link
- $.data[*].sort
- $.data[*].is_show
- $.data[*].file
- $.data[*].image
- $.data[*].__token__
- $.data[*].ban_id
- $.data[*].co_id
- $.data[*].order_id
dependKeyRow_11:
- $.data.data[*].card_manage_id
- $.data.data[*].keys[0]
- $.data.data[*].study_card_name
- $.data.data[*].price
- $.data.data[*].number
- $.data.data[*].least_price
- $.data.data[*].org_id
- $.data.data[*].meth_id
- $.data.data[*].year
- $.data.data[*].month
- $.data.data[*].ticket[0][ticket_manage_id]
- $.data.data[*].ticket[0][ticket_num]
- $.data.data[*].period
dependKeyRow_13:
- $.data.sc_code_id
- $.data.timestamp
- $.data.sign
dependKeyRow_15:
- $.data[*].name
- $.data[*].auth[0]
- $.data[*].auth[2]
- $.data[*].__token__
- $.data[*].id
dependKeyRow_16:
- $.data[*].page
- $.data[*].limit
- $.data[*].keywords
- $.data[*].startDate
- $.data[*].endDate
