SqlExecuteResultRow_16_fw_user:
  keywords: "\u79E6\u654F"
SqlExecuteResultRow_3_nc_course_name:
  course_broker_id: 1
  course_class_id: 12
  course_name: "\u8BB2\u5E08\u987E\u95EE\u73ED\uFF1A\u5BB6\u5EAD\u6559\u80B2\uFF0C\
    \u54C1\u724C\u518D\u9020"
  course_name_id: 40
  course_name_sn: ZB_01_03_0140
  create_admin_id: 0
  create_time: 1551407421
  current_daiding_course_id: 960
  delete_time: 0
  hr_id: 2
  is_auto_legacy: 0
  is_auto_refund: 1
  is_deposit: 0
  is_put: 1
  is_refund_audit: 0
  least_price: 300.0
  legacy_hours: 0
  member_price: 2980.0
  meth_id: 13
  org_id: 1
  perf_comp_id: 0
  price: 2980.0
  update_admin_id: 2727
  update_time: 1578288985
  use_card_number: 1
  use_ticket_number: 1
